name: Simulate a deployment to an environment

on:
    workflow_dispatch:
        inputs:
            target-workspace:
                description: "target workspace for this deployment"
                required: true
                default: "development"
                type: choice
                options:
                    - development
                    - test
                    - production

jobs:
    simulate-deployment:
        runs-on: ubuntu-latest
        environment:
            name: ${{ inputs.target-workspace }}

        steps:
          - name: Checkout repo
            uses: actions/checkout@v2
            with:
                # Take jobs and deploy script from dev branch
                ref: ${{vars.BRANCH_TO_DEPLOY}}
          - name: Simulate deployment
            run: |
                echo "Target workspace: ${{ inputs.target-workspace }}"
                echo "Parameters:"
                echo "  CLIENT_NAME: ${{vars.CLIENT_NAME}}"
                echo "  CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}"
