name: Simulate a check on a pull request

on:
  pull_request:
    #types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  simulate-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0 # We need th get the full history to compare against main
      - name: Simulate Check
        run: |
          echo "This is a simulation of a check on a pull request that fails."
          echo "pwd:"
          pwd
          echo "ls -la:"
          ls -la
          echo "Starting git diff"
          git diff --name-only origin/main..$(git branch --show-current)
          echo "Exiting now with an error..."
          exit 1
