name: Simulate a check on a pull request

on:
  pull_request:
    #types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  simulate-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PR_NUMBER: ${{ github.event.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPO: ${{ github.event.pull_request.head.repo.full_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need to get the full history to compare against main
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
      - name: Simulate Check
        run: |
          echo "This is a simulation of a check on a pull request that fails."
          echo "pwd:"
          pwd
          echo "ls -la:"
          ls -la
          echo "Identifying changed files and posting comments on the PR"
          python check_diffs.py
